language: cpp
sudo: required
dist: trusty
compiler:
- gcc
- clang
os:
- linux
branches:
  only:
  - master
before_script:
  - ./autogen.sh
notifications:
  email:
    - bregma@users.noreply.github.com
  irc:
    channels:
      - "chat.freeode.net#legacy2345"
    template:
      - "%{repository_slug}/%{branch} (%{commit} : %{build_url}) %{message}"
    use_notice: true
    skip_jpin: true
