language: cpp
sudo: required
dist: trusty
compiler:
- gcc
- clang
os:
- linux
branches:
  only:
  - master
before_script:
  - ./autogen.sh
notifications:
  irc:
    channels:
    - chat.freeode.net#legacy2345
    template:
    - "%{repository}/%{branch} (%{commit} - %{author}): %{build_url}: %{message}"
